# Generated by Django 6.0.4 on 2026-05-04 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('messages_sent', models.IntegerField(default=0)),
                ('conversations', models.IntegerField(default=0)),
                ('products_listed', models.IntegerField(default=0)),
                ('avg_reply_time_seconds', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.clientprofile')),
            ],
            options={
                'db_table': 'daily_usage_snapshots',
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
