release: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py seed_plans
web: gunicorn backend.wsgi --workers 2 --bind 0.0.0.0:$PORT --timeout 120
worker: celery -A backend worker --loglevel=info --concurrency=2
beat: celery -A backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
