# Generated by Django 6.0.4 on 2026-05-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('mid__gt', '')), fields=('mid',), name='unique_nonempty_mid'),
        ),
    ]
