# Generated by Django 6.0.4 on 2026-05-04 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], max_length=20, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_groups', models.IntegerField(blank=True, null=True)),
                ('max_workflows', models.IntegerField(blank=True, null=True)),
                ('max_meta_apps', models.IntegerField(blank=True, null=True)),
                ('messages_limit', models.IntegerField(default=2000)),
                ('file_upload_limit', models.BigIntegerField(default=5242880)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation_code', to='accounts.clientprofile')),
            ],
            options={
                'db_table': 'activation_codes',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.clientprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
