# Generated by Django 6.0.4 on 2026-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_paymentrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyusage',
            new_name='monthly_usa_client__49a258_idx',
            old_name='monthly_usa_client__idx',
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='ccp_or_rip',
            field=models.CharField(help_text="Client's CCP/RIP account number used to pay", max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='transfer_reference',
            field=models.CharField(help_text='CCP transfer reference number', max_length=200),
        ),
    ]
