# Generated by Django 6.0.4 on 2026-05-04 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(db_index=True, max_length=100)),
                ('sender_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField()),
                ('forwarded_to', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('forwarded', 'Forwarded'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='received', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['page_id', 'received_at'], name='webhook_log_page_id_6e9610_idx'), models.Index(fields=['status'], name='webhook_log_status_58a1da_idx')],
            },
        ),
    ]
