# Generated by Django 6.0.4 on 2026-05-04 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('conversation_started', 'Conversation Started'), ('product_added', 'Product Added'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('code_verified', 'Activation Code Verified'), ('page_connected', 'Facebook Page Connected'), ('page_disconnected', 'Facebook Page Disconnected'), ('plan_upgraded', 'Plan Upgraded'), ('ai_description', 'AI Description Generated'), ('message_sent', 'Message Sent'), ('group_assigned', 'Group Assigned')], max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='accounts.clientprofile')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='activity_lo_client__7f4fb3_idx')],
            },
        ),
    ]
