# Generated by Django 6.0.4 on 2026-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('conversation_started', 'Conversation Started'), ('product_added', 'Product Added'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('code_verified', 'Activation Code Verified'), ('page_connected', 'Facebook Page Connected'), ('page_disconnected', 'Facebook Page Disconnected'), ('plan_upgraded', 'Plan Upgraded'), ('ai_description', 'AI Description Generated'), ('message_sent', 'Message Sent'), ('group_assigned', 'Group Assigned'), ('trial_expired', 'Trial Expired'), ('order_received', 'Order Received'), ('order_updated', 'Order Updated')], max_length=50),
        ),
    ]
