# Generated by Django 6.0.4 on 2026-05-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='crm_orders_client__439355_idx',
            old_name='crm_orders_client_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='crm_orders_client__475996_idx',
            old_name='crm_orders_client_created_idx',
        ),
    ]
