# Generated by Django 6.0.4 on 2026-05-04 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('electronics', 'Electronics'), ('kids', 'Kids'), ('home', 'Home & Living'), ('sports', 'Sports'), ('food', 'Food & Beverages'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.clientprofile')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='products_client__792d24_idx'), models.Index(fields=['client', 'category'], name='products_client__98f9f6_idx')],
            },
        ),
    ]
